sudo: required
services:
  - docker

before_install:
  - docker build -t vilusluc/multi-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vilusluc/multi-client npm test -- --coverage
#run test

after_success:
  - docker build -t vilusluc/multi-client ./client
  - docker build -t vilusluc/multi-nginx ./nginx
  - docker build -t vilusluc/multi-server ./server
  - docker build -t vilusluc/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push the built images to Docker Hub
  - docker push vilusluc/multi-client
  - docker push vilusluc/multi-nginx
  - docker push vilusluc/multi-server
  - docker push vilusluc/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ca-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ca-central-1-091342932904
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"